import portfolio from "../assets/images/portfolio.svg";
import download from "../assets/images/download.svg";
import linkedIn from "../assets/images/linkedIn.svg";
import gmail from "../assets/images/gmail.svg";
import phone from "../assets/images/phone.svg";
import developer from "../assets/images/developer.svg";
import user from "../assets/images/user.svg";
import company1 from "../assets/images/company1.jpg";
import react from "../assets/images/react.svg";
import html5 from "../assets/images/html5.svg";
import css from "../assets/images/css.svg";
import saas from "../assets/images/saas.svg";
import js from "../assets/images/js.svg";
import bootstrap from "../assets/images/bootstrap.svg";
import redux from "../assets/images/redux.svg";
import motion from "../assets/images/motion.png";
import performance from "../assets/images/performance.png";
import bg1 from "../assets/images/bg1.jpg";
export const PORTFOLIO = portfolio;
export const DOWNLOAD = download;
export const LINKED = linkedIn;
export const GMAIL = gmail;
export const PHONE = phone;
export const DEVELOPER = developer;
export const USER = user;
export const REACT = react;
export const HTML_5 = html5;
export const CSS_5 = css;
export const SAAS = saas;
export const COMPANY1 = company1;
export const JS = js;
export const BOOT = bootstrap;
export const REDUXX = redux;
export const MOTION = motion;
export const PERFORM = performance;
export const BG = bg1;
